Fix bad error message (just removed the summary since it's already being logged via console.error() above anyway)
```
error: Error: Automigrations failed.  (See logs above for help, or continue reading for a summary):: undefined
    at Timeout._onTimeout (/Users/mikermcneil/code/sails-hook-orm/node_modules/waterline-utils/lib/auto-migrations/private/run-alter-strategy/private/inform-re-failed-alter-stratagem.js:192:55)
    at ontimeout (timers.js:488:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:283:5)
```